name: "Docs Build Check"

on:
  push:
    branches: [ master, FABulous2.0-development ]
  pull_request:
    branches: [ master, FABulous2.0-development ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare_FABulous_container
        with:
          install_ghdl_mcode: "false"
      - uses: ammaraskar/sphinx-action@8.2.3
        with:
          pre-build-command: "pip install -r requirements.txt"
          build-command: 'make html SPHINXOPTS+="-W --keep-going -n"'
          docs-folder: "docs/"
